# .travis.yml
language: ruby
rvm:
  - "ruby-2.0.0-p353"
gemfile:
  - Gemfile
before_script:
  - psql -c 'create database terrminology;' -U travis -d postgres
  - bundle exec sequel -m db/migrations postgres:///terrminology
script: rspec spec
